// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestTaskDelivery.Data;

#nullable disable

namespace TestTaskDelivery.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20260529234327_AddTestCities")]
    partial class AddTestCities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.16");

            modelBuilder.Entity("TestTaskDelivery.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameNormalized")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Москва",
                            NameNormalized = "МОСКВА"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Московский",
                            NameNormalized = "МОСКОВСКИЙ"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Москворечье",
                            NameNormalized = "МОСКВОРЕЧЬЕ"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Санкт-Петербург",
                            NameNormalized = "САНКТ-ПЕТЕРБУРГ"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Петергоф",
                            NameNormalized = "ПЕТЕРГОФ"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Новосибирск",
                            NameNormalized = "НОВОСИБИРСК"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Сибирский",
                            NameNormalized = "СИБИРСКИЙ"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Казань",
                            NameNormalized = "КАЗАНЬ"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Казанка",
                            NameNormalized = "КАЗАНКА"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Ростов-на-Дону",
                            NameNormalized = "РОСТОВ-НА-ДОНУ"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Ростов Великий",
                            NameNormalized = "РОСТОВ ВЕЛИКИЙ"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Краснодар",
                            NameNormalized = "КРАСНОДАР"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Красноярск",
                            NameNormalized = "КРАСНОЯРСК"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Владивосток",
                            NameNormalized = "ВЛАДИВОСТОК"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Владимир",
                            NameNormalized = "ВЛАДИМИР"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Волгоград",
                            NameNormalized = "ВОЛГОГРАД"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Вологда",
                            NameNormalized = "ВОЛОГДА"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Воронеж",
                            NameNormalized = "ВОРОНЕЖ"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Екатеринбург",
                            NameNormalized = "ЕКАТЕРИНБУРГ"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Екатериновка",
                            NameNormalized = "ЕКАТЕРИНОВКА"
                        });
                });

            modelBuilder.Entity("TestTaskDelivery.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PickupDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReceiverAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ReceiverCityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SenderAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SenderCityId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Weight")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.HasIndex("ReceiverCityId");

                    b.HasIndex("SenderCityId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("TestTaskDelivery.Models.Order", b =>
                {
                    b.HasOne("TestTaskDelivery.Models.City", "ReceiverCity")
                        .WithMany()
                        .HasForeignKey("ReceiverCityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TestTaskDelivery.Models.City", "SenderCity")
                        .WithMany()
                        .HasForeignKey("SenderCityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReceiverCity");

                    b.Navigation("SenderCity");
                });
#pragma warning restore 612, 618
        }
    }
}
