// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestTaskDelivery.Data;

#nullable disable

namespace TestTaskDelivery.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20260529233105_AddNameNormalizedToCities")]
    partial class AddNameNormalizedToCities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.16");

            modelBuilder.Entity("TestTaskDelivery.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameNormalized")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Москва",
                            NameNormalized = "МОСКВА"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Санкт-Петербург",
                            NameNormalized = "САНКТ-ПЕТЕРБУРГ"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Новосибирск",
                            NameNormalized = "НОВОСИБИРСК"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Екатеринбург",
                            NameNormalized = "ЕКАТЕРИНБУРГ"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Казань",
                            NameNormalized = "КАЗАНЬ"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Нижний Новгород",
                            NameNormalized = "НИЖНИЙ НОВГОРОД"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Челябинск",
                            NameNormalized = "ЧЕЛЯБИНСК"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Омск",
                            NameNormalized = "ОМСК"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Ростов-на-Дону",
                            NameNormalized = "РОСТОВ-НА-ДОНУ"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Уфа",
                            NameNormalized = "УФА"
                        });
                });

            modelBuilder.Entity("TestTaskDelivery.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PickupDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReceiverAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ReceiverCityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SenderAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SenderCityId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Weight")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.HasIndex("ReceiverCityId");

                    b.HasIndex("SenderCityId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("TestTaskDelivery.Models.Order", b =>
                {
                    b.HasOne("TestTaskDelivery.Models.City", "ReceiverCity")
                        .WithMany()
                        .HasForeignKey("ReceiverCityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TestTaskDelivery.Models.City", "SenderCity")
                        .WithMany()
                        .HasForeignKey("SenderCityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReceiverCity");

                    b.Navigation("SenderCity");
                });
#pragma warning restore 612, 618
        }
    }
}
